apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student-backend
  template:
    metadata:
      labels:
        app: student-backend
    spec:
      containers:
      - name: student-backend
        image: sarangasl/student-management-backend:latest
        imagePullPolicy: Always
        env:
        - name: PORT
          value: "3001"
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: student-backend
spec:
  selector:
    app: student-backend
  type: NodePort
  ports:
    -  port: 3001
       targetPort: 3001
       nodePort: 32000